stages:
  create_dataset:
    cmd: python create_dataset.py
    deps:
    - utils.py
    outs:
    - assets/download/dataset.csv
    - assets/dataset/train.csv
    - assets/dataset/test.csv

  create_features:
    cmd: python create_features.py
    deps:
    - utils.py
    outs:
    - assets/features/train_features.csv
    - assets/features/test_features.csv
    - assets/features/train_labels.csv
    - assets/features/test_labels.csv